### ISSUE TITLE
Hl signals

### ISSUE THREAD

**Issue by ghost** [sb12/OSMTrainRouteAnalysis#63] opened 2015-08-22 21:39 UTC
If the distance to next main is below 700 m the Hl signal should signal 100 km/h (if it is not the maxspeed of the track).

The green and yellow stripes don't exist at every signal. If the signal can only show Hp0, Hl1, Hl3a, Hl4, Hl6a, Hl7, Hl9a, Hl10, Hl12a, the signal has no stripes.

Some signals only have one of the stripes. In that case the other stripes should not be rendered, even not gray.

**Comment by sb12** [comment] 2015-08-23 09:07
Thank you for your feedback.
I'm not familiar with the Hl signalling system, so if you find more bugs or unexpected behaviour please let me know.

**Comment by PeterDRS** [comment] 2015-08-23 12:21
What's the meaning of closing an issue? That it is solved?

In this case it isn't.

**Comment by sb12** [comment] 2015-08-23 12:36
> What's the meaning of closing an issue? That it is solved?

In this case yes.

> In this case it isn't.

What is not solved?

**Comment by PeterDRS** [comment] 2015-08-23 12:39
If found a new bug #69 

A signal which can only show Hl11 or Hl8, but not Hl1, is shown as Hl1.

**Comment by PeterDRS** [comment] 2015-08-23 12:48
Please reopen this issue again.
In route 3705112 the signal 524 shows Hl8.

**Comment by sb12** [comment] 2015-08-24 16:54
>Please reopen this issue again.

Ok. Let's have a "report all hl errors here" issue.

**Comment by sb12** [comment] 2015-08-24 16:58
> In route 3705112 the signal 524 shows Hl8

Combination of #32 and #69 and maybe wrong interpretation of Hl signalling system.

**Comment by sb12** [comment] 2015-08-24 17:00
Question about the Hl system:
Is Hl1 only shown when the track speed is higher than 100 km/h or can it also be shown when it is lower.
What if the track speed is 60 km/h, does it show Hl1 or Hl3b?

**Comment by PeterDRS** [comment] 2015-08-24 17:04
It shows Hl1 = vmax, if there are no switches or other things that need a differenciation. In case of vmax = 100 or vmax = 60 it shows Hl1 when the switch is straight, otherwise it shows Hl3b, even if it is the same speed (vmax is already 60).

The problem is that it is hard to differenciate between speed limits that are static and not shown by Hl signals.

**Comment by PeterDRS** [comment] 2015-08-24 17:07
There are Hl signals that are so called "Automatikblock AB 70". They have a Mastschild yellow - white and look different.

http://www.veb-verkehr.de/betrieb/bilder/obj/hl-signale.jpg

The signal 4-5-6 from the left.

Should we introduce a special tagging?

railway:signal:main:function=automatic_block

?

It also occurs in other signal systems.

**Comment by PeterDRS** [comment] 2015-08-26 17:35
I have found good literature: http://www.amazon.de/Handbuch-ESTW-Funktionen-Sicherungsebene-Elektronischen-Stellwerk/dp/387814802X

Perhaps you can also find it in a library.

Main idea for speed signalisation is to split up speeds in those with Lf7 and those without. That would be a beginning. ;)

Additionally, it would be nice to determine in which state a switch is passed - but how? That's a geometric issue, as long as there are no relations saying which way is which part of a switch.

**Comment by sb12** [comment] 2016-10-08 20:07
The problems with hl signals mentioned in this issue should be fixed. If anybody finds a specific situation where signals show another state in OSM than in reality, feel free to open a new issue and I'll see if it can be fixed.

**Closed by sb12** 2016-10-08 20:07 UTC
Labels: bug, signals
