### ISSUE TITLE
Combined signals with no distant state (Entry/Block)

### ISSUE THREAD

**Issue by ghost** [sb12/OSMTrainRouteAnalysis#61] opened 2015-08-22 20:42 UTC
In route http://osmtrainroutes.bplaced.net/beta/index.php?id=5372939 the signal 2528135655 is used as a block signal (not entry signal like for other routes).

In this function (no connected main signal to announce) the signal jumps from Hp0 to Ks1 directly (seen in reality). The state Ks2 cannot be shown in this case.

**Comment by sb12** [comment] 2015-08-22 21:00
So we would need to assume that all combined signals that do not have a main signal in the next 1500 m or have a distant signal in between do behave like main signals.

**Comment by PeterDRS** [comment] 2015-08-22 21:05
Yes. Additionally, the function could be tagged like this:
railway:signal:combined:function=entry;block

Some signals are intermediate or exit. They could be tagged like this:
railway:signal:combined:function=intermediate;exit

Such signals indicate that everything is correct. In this case the "?" should not be displayed.

**Comment by PeterDRS** [comment] 2015-08-22 21:10
The equivalent for this in H/V is that the Vr distant signal stays completely off. It even does not show Kennlicht. The Hp signal is responsible for this: If it shows Hp1 or Hp2, everything is correct, the Vr is not broken. If the Vr should be used and is broken it would stay at Hp0.

So change the code that Vr distant can have the state "off" meaning showing absolutely NOTHING. ;)

**Comment by sb12** [comment] 2016-09-03 20:34
This is solved for Vr signals. 
Not sure what to do about Ks signals, the problem is that it will throw too many false positives with the currently available data if I just assume that all ks signals can go from hp0 directly to ks1 if there's no other main signal. Best solution is probably to just show an information that it could be correct that there is no main signal afterwards. Another possibility is a new tag that informs about this specific fact (The above mentioned `block;entry` does not help much, as it does not necessarily have something to do with whether there is a corresponding main signal or not)

**Comment by Nakaner** [comment] 2016-09-04 10:51
I think that this a rather exotic case (after mapped and travelled a lot in Germany by train). I could even imagine a combined entry signal which shows only Hp 0 and Ks 1 for a routes without a main/combined signal within the next 1300 metres while being able to show Ks 2 for routes where no dedicated distant signal follows because the next main/combined signals is not as far away.

The original complain refers to only one case where it occurs and I therefore suggest to close it.

**Closed** 2016-09-04 11:34 UTC
Labels: bug, signals
