### ISSUE TITLE
If stop position does not have a name, use name of the stop positions's stop area instead of showing "Unbekannte Haltestelle" (unknown stop)

### ISSUE THREAD

**Issue by Hans-Mueller** [sb12/OSMTrainRouteAnalysis#107] opened 2016-02-18 15:03 UTC
Problem: In OMS, giving a name to a stop position is only optional, if it is element of a stop area. See http://wiki.openstreetmap.org/wiki/Proposed_features/Public_Transport#Stop_position. Thus, we have stop positions in OSM without a name. See for example relation https://www.openstreetmap.org/relation/5626115. Currently this results in osmtrainroutes showing "Unbekannte Haltestelle" (English: Unknown stop), see for example http://osmtrainroutes.bplaced.net/beta/index.php?id=5626115&train=LINT41

Solution: In cases, when a stop position does not have a name, but is element of a stop area, the name of the stop position's stop area should be pulled and used as the name of the stop position.

**Comment by Nakaner** [comment] 2016-02-18 17:36
see discussion at https://www.openstreetmap.org/changeset/37206710

**Comment by DerDakon** [comment] 2016-05-11 16:56
Duplicate of #2.

**Closed** 2016-05-11 17:01 UTC
Labels: enhancement, stops
